name: Publish Release Draft

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install jq
        run: sudo apt-get install -y jq
      - name: Get latest release
        run: |
          RELEASE_ID=$(curl -s https://api.github.com/repos/IntellectualSites-Internal/plotsquared-github-action-demo/releases/latest | jq '.id')
          echo "Release ID: $RELEASE_ID"
      
      # Check if the release is a draft
      - name: Check draft status
        if: ${{ env.RELEASE_ID }} != null
        run: |
          RELEASE_DRAFT=$(curl -s https://api.github.com/repos/IntellectualSites-Internal/plotsquared-github-action-demo/releases/$RELEASE_ID | jq '.draft')
          echo "Release draft: $RELEASE_DRAFT"
          if [ "$RELEASE_DRAFT" = "true" ]; then
            echo "yay!"
            exit 1
          fi
